chain:
  id: gaia
  name: cosmos
db:
  host: localhost
  port: 5432
  user: cosmscan
  password: cosmscan
  database: cosmscan
log:
  environment: development
  level: info
start_block: 1
rpc_endpoint: http://localhost:26657/